import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    accordion: 'src/accordion/index.ts',
    checkbox: 'src/checkbox/index.ts',
    dialog: 'src/dialog/index.ts',
    'dropdown-menu': 'src/dropdown-menu/index.ts',
    label: 'src/label/index.ts',
    'radio-group': 'src/radio-group/index.ts',
    select: 'src/select/index.ts',
    separator: 'src/separator/index.ts',
    switch: 'src/switch/index.ts',
    slider: 'src/slider/index.ts',
    tabs: 'src/tabs/index.ts',
    'context-menu': 'src/context-menu/index.ts',
    popover: 'src/popover/index.ts',
    tooltip: 'src/tooltip/index.ts',
    'hover-card': 'src/hover-card/index.ts',
    'alert-dialog': 'src/alert-dialog/index.ts',
    avatar: 'src/avatar/index.ts',
    'aspect-ratio': 'src/aspect-ratio/index.ts',
    'scroll-area': 'src/scroll-area/index.ts',
    progress: 'src/progress/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  external: ['@radix-ui/primitive'],
});
